name: Continuous Integration
on:
  push:
    branches-ignore:
      - "main"
env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ vars.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  STRAVA_CLIENT_ID: ${{ vars.STRAVA_CLIENT_ID }}
  STRAVA_CLIENT_SECRET: ${{ vars.STRAVA_CLIENT_SECRET }}

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Use Variables
        run: |
          echo "nextauth url variable : $NEXTAUTH_URL"
      - name: Begin linting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Begin Testing
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
